version: 2
updates:
  # Fetch and update latest `gradle` packages
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - jforatier
    assignees:
      - jforatier
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `gradle` packages
  - package-ecosystem: gradle
    directory: '/app'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - jforatier
    assignees:
      - jforatier
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - jforatier
    assignees:
      - jforatier
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
